name: Update Modrinth Description
on:
  push:
    branches: [ master ]
jobs:
  modrinth-desc:
    runs-on: ubuntu-fat
    steps:
    - uses: actions/checkout@v7
    - uses: https://github.com/funnyboy-roks/modrinth-auto-desc@v1.7
      with:
        auth-token: ${{ secrets.MODRINTH }}
        slug: 'oBZj9E15'